### PR TITLE
Feature/transects quadrats as samples

### PR DESCRIPTION
**Pull request by edmondchuc**
Add
- sosa:isSampleOf a transitive property
- ManagedFeature class

Remove
- tern:siteType
- references to the Site for Sampling and Observation
- duplicate properties in subclasses (I have a handy python script for this)
- file `tern.shacl.shapes.shapes.ttl` - no longer needed as the main ontology `tern.ttl` now defines SHACL constraints

### CODE REVIEW

**Comment by edmondchuc** [comment]
ManagedFeature diagram

@dr-shorthair I just want to clarify how the ManagedFeature class is intended to be used.

Any feature-of-interest can be an instance of Sample with ManagedFeature as a mixin class. 

ManagedFeature usage

Plot_1 and Subplot_1 are instances of Sample as well as instances of the ManagedFeature class. Therefore, they must record the commissioned date and optionally record the decommissioned date. 

Is this how you imagine using this ManagedFeature class? Thanks.

**Comment by dr-shorthair** [comment]
> Is this how you imagine using this ManagedFeature class?

Yep. You got it.

**Comment by dr-shorthair** [comment]
Did you see my comment about cardinality of `tern:featureType` property. It is plausible that a sample (or another feature) might be classified with more than one feature-type. 

However, I know unlimited cardinality is difficult for a database.

**Comment by edmondchuc** [comment]
Yes I did see your comment on the cardinality of `tern:featureType`. I have some thoughts below. 

I agree in some cases there may be multiple feature types. However, most of the time the multiple feature types are either a narrower or broader relationship to the single explicit feature type declared in the data. From a data exchange perspective, it makes it a bit simpler to have only one feature type. And when required, generate the additional feature types from the broader relationships defined in the concept scheme. This means our current set of constraints may only be suitable for data exchange and it may be appropriate to have a different set of constraints like having `min 1` instead of `exactly 1` for a data integration system. 

Another perspective from an application level (our EcoPlots web app), it may be problematic to show multiple feature types in a table-based data structure. See below where we show the feature type of an observation's feature of interest. 

EcoPlots data table

These are some of the thoughts I had.

**Comment by dr-shorthair** [comment]
Good analysis. I agree that most often multiple types could have relationships in the vocab hierarchy. And I suspected there would be a other side-effects, which was why I only made it a comment. 

Leave it as 1 for the moment, and only consider changing, or a work-around, if a real need appears in the data.

**Review by dr-shorthair — APPROVED** [review]

**Pull request merged**
