### PR TITLE
Remove sh:maxCount on sosa:isResultOf property of tern:Result

### PR DESCRIPTION
**Pull request by edmondchuc**

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Does this mean that a Result can be the product of more than one action?

**Comment by edmondchuc** [comment]
Yes, but I don't have any ecological examples. 

I changed it simply because I was browsing the SSN's documentation and noticed their OWL restriction states it expects a minimum of 1 `sosa:isResultOf` relationship. 

See [SOSA Result](https://www.w3.org/TR/vocab-ssn/#SOSAResult).

I was planning to ensure we are aligned to SOSA/SSN before providing reasons as to why it should be constrained further.

@dr-shorthair can you think of any examples where a `Result` is from more than one `Activity`?

**Comment by miekeGR** [comment]
Just checking the inverse on Observations. Is it still the case that Observations can have only "Exactly 1" sosa:hasResult?

**Comment by dr-shorthair** [comment]
> @dr-shorthair can you think of any examples where a Result is from more than one Activity?

No, unless you decompose an activity into pieces, but then it is still last of these that actually generates the result

> Is it still the case that Observations can have only "Exactly 1" sosa:hasResult?

Yes. That is a basic tenet of O&M. It also makes the representation simpler (though possibly more verbose, but that is not a sin). 

A result can be 'complex' (but this is only advisable for things like vectors quantities, or raster data like imagery - no-one would suggest making each component of a vector, or pixel from an image into a separate result!). 
But you need more than one Observation to generate more than one result.

**Comment by edmondchuc** [comment]
> No, unless you decompose an activity into pieces, but then it is still last of these that actually generates the result

That's what I was thinking as well. Multiple activities chained together and only the last one will produce the result of interest.

**Pull request merged**
